### ISSUE TITLE
Functional Stateless Components

### ISSUE THREAD

**Issue by mikekidder** [ryanluker/typed-catch-of-the-day#22]
Hi Ryan, not really an issue.  Just wanted to say nice work on putting this version together.  I think I am totally sold on the React/Typescript combo.

Was going to submit a PR to showcase stateless components but realized it would break your tests.  Have you seen anything to test for Functional Stateless Components via React Addon Utils?

**Comment by mikekidder** [comment]
Actually, found something here. https://github.com/iamdustan/react-testing-stateless-components

**Comment by ryanluker** [comment]
hey mike, thanks for the kind words about the repository! I put up a quick PR that upgrades the project typescript to 1.8.2 and the react.d.ts (needed for stateless components). I also added a simple stateless component (AddFishButton) but ran into testing trouble with jest like you mentioned...
